name: Docker build and test

on: [push,pull_request]

jobs:
  build:
   runs-on: ubuntu-latest
  
   steps:
     - uses: actions/checkout@v2
     - name: Build Docker image 
       run: docker build --tag topic-detection:action .
     - name: Run Docker container
       run: docker run -p 0.0.0.0:5000:5000/tcp -d --name topic-detection-action topic-detection:action 
     - name: Sleep for 10s
        uses: juliangruber/sleep-action@v1
        with:
          time: 10s

     - name: Run tests inside the container
       run: docker exec topic-detection-action pytest 
     
